name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build - ${{ matrix.platform.os }} (${{ matrix.platform.target }})
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: amnesia
            asset_name: amnesia-linux-x86_64.tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            bin: amnesia
            asset_name: amnesia-macos-x86_64.tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            bin: amnesia
            asset_name: amnesia-macos-aarch64.tar.gz

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout content
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Archive binary
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar -czf ../../../${{ matrix.platform.asset_name }} ${{ matrix.platform.bin }}
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.asset_name }}
          path: ${{ matrix.platform.asset_name }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
